language: node_js
node_js: '12'
env:
  global:
    - GIT_NAME="Domain Management"
    - GIT_EMAIL="domain.management@americastestkitchen.com"

git:
  depth: false

install:
  - yarn

script:
  - yarn build
  - yarn tsc

deploy:
  - provider: script
    script: if [ "$GH_TOKEN" != "false" ];then npx auto shipit; fi;
    skip-cleanup: true
    on:
      branch: main
